---
# Almost all linters; some of them are optional.

run:
  skip-dirs:
    - bogus

  modules-download-mode: readonly

linters-settings:
  govet:
    check-shadowing: true
  goimports:
    local-prefixes: gopkg.in/reform.v1

linters:
  enable-all: true
  disable:
    - gomnd        # too annoying
    - lll          # too annoying
    - testpackage  # too annoying
    - wsl          # too annoying

issues:
  exclude-use-default: false
  exclude:
    # gosec - we are making an ORM after all
    - "G201: SQL string formatting"
    - "G202: SQL string concatenation"
    # golint - matches database/sql.Result.LastInsertId()
    # > method LastInsertIdMethod should be LastInsertIDMethod
    # > type `LastInsertIdMethod` should be `LastInsertIDMethod`
    # > var `lastInsertIdMethod` should be `lastInsertIDMethod`
    - "`?LastInsertIdMethod`? should be `?LastInsertIDMethod`?"
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen       # tests may be long
        - testpackage  # senseless
        - unused       # very annoying false positive: https://github.com/golangci/golangci-lint/issues/791
