---
# The most valuable linters; they are required to pass for PR to be merged.

run:
  skip-dirs:
    - bogus

  modules-download-mode: readonly

linters-settings:
  govet:
    check-shadowing: true
  goimports:
    local-prefixes: gopkg.in/reform.v1

linters:
  disable-all: true
  enable:
    - depguard
    - goimports
    - govet
    - ineffassign
    - nolintlint
    - staticcheck

issues:
  exclude-use-default: false
