---
# Almost all linters; some of them are optional.

run:
  skip-dirs:
    - bogus

  modules-download-mode: readonly

linters-settings:
  govet:
    check-shadowing: true
  goimports:
    local-prefixes: gopkg.in/reform.v1

linters:
  enable-all: true
  disable:
    - gomnd        # too annoying
    - lll          # too annoying
    - testpackage  # too annoying
    - wsl          # too annoying

issues:
  exclude-use-default: false
  exclude:
    # gosec
    - "G201: SQL string formatting"
    - "G202: SQL string concatenation"
    - "G204: Subprocess launched with variable"
    - "G304: Potential file inclusion via variable"
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen       # tests may be long
        - testpackage  # senseless
        - unused       # very annoying false positive: https://github.com/golangci/golangci-lint/issues/791
