dist: bionic
language: go

services:
  - docker

go:
  - master

go_import_path: gopkg.in/reform.v1

cache:
  directories:
    - /home/travis/.cache/go-build
    - /home/travis/gopath/pkg/mod

env:
  global:
    - GO111MODULE=on
    - GOPROXY=https://proxy.golang.org
    - GOFLAGS="-mod=readonly"
    - GORACE="halt_on_error=1"
    - REFORM_MSSQL_IMAGE=microsoft/mssql-server-linux:latest

  matrix:
    - REFORM_POSTGRES_IMAGE=postgres:9.6 REFORM_MYSQL_IMAGE=mysql:5.5
    - REFORM_POSTGRES_IMAGE=postgres:10  REFORM_MYSQL_IMAGE=mysql:5.6
    - REFORM_POSTGRES_IMAGE=postgres:11  REFORM_MYSQL_IMAGE=mysql:5.7
    - REFORM_POSTGRES_IMAGE=postgres:12  REFORM_MYSQL_IMAGE=mysql:8.0

before_install:
  - env
  - go version
  - go env
  - pwd
  - ls -al
  - docker --version
  - docker-compose --version

  - make env-up-detach

install:
  - go mod download

  # check that it is still possible to install reform without modules
  - env GO111MODULE=off go get -v ./...
  - reform -version
  - reform-db -version

  - make init

  - make env-up-wait

script:
  - make test

  # TODO test again with updated deps

  - git status
  - git diff --exit-code

after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage.txt -X fix -e REFORM_POSTGRES_IMAGE,REFORM_MYSQL_IMAGE,REFORM_MSSQL_IMAGE
