version: '{build}'

clone_folder: c:\gopath\src\gopkg.in\reform.v1

environment:
  GOPATH: c:\gopath
  GO111MODULE: on
  GOFLAGS: -mod=readonly
  GORACE: halt_on_error=1

  matrix:
    - REFORM_MAKE_TARGET: sqlite3

    - REFORM_SQL_INSTANCE: SQL2008R2SP2
      REFORM_MAKE_TARGET: win-mssql
    - REFORM_SQL_INSTANCE: SQL2008R2SP2
      REFORM_MAKE_TARGET: win-sqlserver

    - REFORM_SQL_INSTANCE: SQL2012SP1
      REFORM_MAKE_TARGET: win-mssql
    - REFORM_SQL_INSTANCE: SQL2012SP1
      REFORM_MAKE_TARGET: win-sqlserver

    - REFORM_SQL_INSTANCE: SQL2014
      REFORM_MAKE_TARGET: win-mssql
    - REFORM_SQL_INSTANCE: SQL2014
      REFORM_MAKE_TARGET: win-sqlserver

    - REFORM_SQL_INSTANCE: SQL2016
      REFORM_MAKE_TARGET: win-mssql
    - REFORM_SQL_INSTANCE: SQL2016
      REFORM_MAKE_TARGET: win-sqlserver

install:
  - if defined REFORM_SQL_INSTANCE powershell -file .github\appveyor-prepare-mssql.ps1
  - set PATH=C:\msys64\usr\bin;C:\msys64\mingw64\bin;%GOPATH%\bin;%PATH%
  - pacman -Rsc --noconfirm gcc

  - go version

build_script:
  # check that it is still possible to install everything without modules
  - env GO111MODULE=off go get -v ./...
  - reform -version
  - reform-db -version

  - go mod download

  - make init

test_script:
  - make test-unit
  - make $(REFORM_MAKE_TARGET)

  # TODO test again with updated deps

  - git status
  - git diff --exit-code

on_success:
  - curl -s -o codecov https://codecov.io/bash
  - bash codecov -f coverage.txt -X fix -e REFORM_MAKE_TARGET,REFORM_SQL_INSTANCE
