---
name: Cleanup
on:
  schedule:
    # Saturday 7:00
    - cron: "0 7 * * 6"

jobs:
  clean:
    name: Clean caches
    timeout-minutes: 5

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        go-version:
          - 1.13.x
          - 1.14.x
          - 1.15.x
          - tip

    runs-on: ${{ matrix.os }}

    env:
      WORKDIR: "${{ github.workspace }}/gopath/src/gopkg.in/reform.v1"
      GOPATH: "${{ github.workspace }}/gopath"
      GOBIN: "${{ github.workspace }}/gopath/bin"
      GO111MODULE: "on"
      GOPROXY: "https://proxy.golang.org"

    steps:
      - name: Enable Go modules cache
        uses: actions/cache@v2
        with:
          path: ${{ env.GOPATH }}/pkg/mod
          key: ${{ matrix.os }}-go-${{ matrix.go-version }}-modules-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ matrix.os }}-go-${{ matrix.go-version }}-modules-

      - name: Enable Go build cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/go-build
          key: ${{ matrix.os }}-go-${{ matrix.go-version }}-build-${{ github.ref }}-${{ hashFiles('**') }}
          restore-keys: |
            ${{ matrix.os }}-go-${{ matrix.go-version }}-build-${{ github.ref }}-
            ${{ matrix.os }}-go-${{ matrix.go-version }}-build-

      - name: Set up Go version ${{ matrix.go-version }}
        if: matrix.go-version != 'tip'
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Set up Go tip
        if: matrix.go-version == 'tip'
        run: |
          git clone --depth=1 https://go.googlesource.com/go $HOME/gotip
          cd $HOME/gotip/src
          ./make.bash
          echo "GOROOT=$HOME/gotip" >> $GITHUB_ENV
          echo "$HOME/gotip/bin" >> $GITHUB_PATH

      - name: Check out code into GOPATH
        uses: actions/checkout@v2
        with:
          path: ${{ env.WORKDIR }}

      - name: Clean Go modules cache
        run: go clean -modcache

      - name: Clean Go build cache
        run: go clean -cache
